---
- name: Install chrony
  ansible.builtin.apt:
    name: chrony
    state: present

- name: Configure NTP servers
  ansible.builtin.template:
    src: chrony.conf.j2
    dest: /etc/chrony/chrony.conf
    owner: root
    group: root
    mode: "0644"
  notify: Restart chrony

- name: Set timezone
  community.general.timezone:
    name: "{{ ntp_timezone }}"

- name: Ensure chrony is enabled and running
  ansible.builtin.systemd:
    name: chrony
    enabled: true
    state: started
